### ISSUE TITLE
Restylen der Listenseite

### ISSUE THREAD

**Issue by p-runge** [Marvin-Dem/Pokacid#20]
Die aktuelle Listenseite sieht noch etwas nach Wachsmalkreide aus. Überlege dir ein saubereres Design für eine Listenansicht und setze diese um.

# ToDos

- [x] Neue Liste designen
- [x] Design abnehmen lassen und technisch besprechen
- [x] Umsetzen des neuen Designs

**Comment by Marvin-Dem** [comment]
Versehentlich Ticket #20 und #21 vertauscht
