### ISSUE TITLE
Hinzufügen einer Rasteransicht

### ISSUE THREAD

**Issue by p-runge** [Marvin-Dem/Pokacid#21]
Viele Apps erlauben es dem User in Listen zwischen einer normalen Listen- und einer Rasteransicht zu wechseln.

Hier mal ein Beispiel:

- https://codepen.io/p-runge/pen/QWewRaZ

Eine solche Funktionalität wäre auch für die Listenseite in Pokacid hilfreich.

# ToDos

- [x] Rasteransicht für die Listenseite designt
- [x] Design abnehmen lassen
- [ ] Überlegung zu Markup Struktur gemacht, damit Items in Listen- und Rasteransicht möglichst das gleiche Markup benutzen können und nur über das Styling variieren
- [ ] Toggle Element eingefügt um zwischen Listen- und Rasteransicht wechseln zu können
- [ ] Rasteransicht gebautViele Apps erlauben es dem User in Listen zwischen einer normalen Listen- und einer Rasteransicht zu wechseln.

Hier mal ein Beispiel:

- https://codepen.io/p-runge/pen/QWewRaZ

Eine solche Funktionalität wäre auch für die Listenseite in Pokacid hilfreich.

# ToDos

- [ ] Rasteransicht für die Listenseite designt
- [ ] Design abnehmen lassen
- [ ] Überlegung zu Markup Struktur gemacht, damit Items in Listen- und Rasteransicht möglichst das gleiche Markup benutzen können und nur über das Styling variieren
- [ ] Toggle Element eingefügt um zwischen Listen- und Rasteransicht wechseln zu können
- [ ] Rasteransicht gebaut

**Comment by p-runge** [comment]
Dieses Ticket erst nach #20 bearbeiten

**Comment by p-runge** [comment]
This issue will be reopened being connected to the new "General" project of Progani.
