### ISSUE TITLE
Hinzufügen einer Rasteransicht

### ISSUE THREAD

**Issue by p-runge** [Marvin-Dem/Pokacid#28]
Viele Apps erlauben es dem User in Listen zwischen einer normalen Listen- und einer Rasteransicht zu wechseln.

Hier mal ein Beispiel:

- https://codepen.io/p-runge/pen/QWewRaZ

Eine solche Funktionalität wäre auch für die Listenseite in Pokacid hilfreich.

# ToDos

- [x] Rasteransicht für die Listenseite designt
- [x] Design abnehmen lassen
- [x] Toggle Element einfügen um zwischen Listen- und Rasteransicht wechseln zu können
- [x] Layout für Rasteransicht bauen
- [x] Zweite PokemonCard Komponente für Grid-Ansicht anlegen
- [x] Je nach Ansicht entweder die eine oder die andere PokemonCard Komponente rendern

**Comment by Marvin-Dem** [comment]
![Image](https://github.com/user-attachments/assets/7c2bc563-6838-4c73-9f71-d8d9dc217809)

**Comment by Marvin-Dem** [comment]
![Image](https://github.com/user-attachments/assets/15558412-d7fa-4f33-80f0-0923778dcc01)
