### ISSUE TITLE
Create About Me Page

### ISSUE THREAD

**Issue by p-runge** [Marvin-Dem/Pokacid#29]
There is an about me button(?) in the footer of the page that does nothing at the moment. There should be a new page designed and built that gives some information about the author.

# ToDo

- [x] Think of what things should be added to the about me page
- [x] Design the about me page
- [x] Get approval for the design
- [x] ~~Create a new page "about-me" and build the regarding component~~

**Comment by Marvin-Dem** [comment]
Took Linktree Design from Mimo for the About me Page

**Comment by p-runge** [comment]
Todos for making the "about me" page an external site:

- [x] Create a new repository on GitHub
- [x] Set up a new project locally (e.g. by using `npm create vite`)
- [x] Use your Mimo "linktree" project's code and render it in your app
- [x] Import your new GitHub repo as a new project in Vercel
- [x] Make the project be accessible publicly (test in icognito mode)
- [x] Link the absolute URL to your "about me" button in Pokacid
