### ISSUE TITLE
Update Home Page

### ISSUE THREAD

**Issue by p-runge** [Marvin-Dem/Pokacid#30]
The home page is in an unfinished state. It should get some (but not too much) content and get designed in a prettier way.

# ToDo

- [x] Think of a few things to add to the home page
- [x] Design the home page
- [x] Get approval for the design
- [x] Build the updated page
