### ISSUE TITLE
Add Static Branding

### ISSUE THREAD

**Issue by p-runge** [Marvin-Dem/Pokacid#31]
The website's branding (colors, logo, etc.) is not really thought through at the moment. The main background color is pretty random and there is no Pokémon-related design at all. This should be changed.

# ToDo

- [x] Create a logo using online tools, AI or whatever
- [x] Think of a main background
- [x] Design a general branding based on those things for the basic layout of the website including colors, fonts and space sizes
- [x] Get approval for the design
- [x] Add the design definitions to the Tailwind config
- [x] Use the new design definitions on the whole website

**Comment by Marvin-Dem** [comment]
![Image](https://github.com/user-attachments/assets/d09ad9a6-5e5e-4ee7-9f3a-fcaaf9b6ed8d)

**Comment by Marvin-Dem** [comment]
These are the background colors i chose for Pokacid. There are three different variations, based on which colortheme you choose.
