### ISSUE TITLE
Update Layout to Be Responsive

### ISSUE THREAD

**Issue by p-runge** [Marvin-Dem/Pokacid#35]
The current layout has its main content shifted to the right and is not following the "boxed design" principle. That shall be changed.

# ToDos

- [x] Make the main content follow the "boxed design" principle by adding Tailwind's class `container` to it
- [x] Make the main layout have spacing in a way that leads to the main content being centered on the page
- [x] Make sure paddings / margins are set in a way that makes sense in the layout
- [x] Test different viewports on different pages and potentially update them in the Tailwind config
