### ISSUE TITLE
Update Detail Page Layout

### ISSUE THREAD

**Issue by p-runge** [Marvin-Dem/Pokacid#40]
# ToDos

- [x] Fix size of play button and relocate it
- [x] Add background to sprite
- [x] Add background colors to type buttons
- [x] Fix main content padding to consider expanded sidebar
- [x] Restyle whole page to use Tailwind classes

The goal of the last todo is to make the `global.css` file as slim as possible.
