### ISSUE TITLE
Responsive Detail Page

### ISSUE THREAD

**Issue by p-runge** [Marvin-Dem/Pokacid#41]
# ToDos

- [x] Define a column based layout for the "main content" aka the root element of your page (not in the layout component)
  - [x] Define a unified gap size for the grid
  - [x] Define an amount of columns for each viewport
- [x] Make your "top level wrapper elements" in your layout span over the necessary columns of the main grid
- [x] Relocate all your major elements within those wrapper elements while honoring the grid of the main container

Regarding the last bullet point:

**Since your elements won't be DIRECT children of the main container aka "the grid parent", it will be necessary to use CSS [subgrid](https://tailwindcss.com/docs/grid-template-columns#subgrid).**

- [x] Relocate your elements also for the mobile viewport using [Tailwind's viewport modifiers](https://tailwindcss.com/docs/responsive-design).

**Comment by Marvin-Dem** [comment]
Desktop view(1440px): Grid of 12 columns, Gap of 16px -> Column width of 72px

Mobile view(380px): Grid of 4 columns, Gap of 16px -> Column width of 83px
