### ISSUE TITLE
Update Header

### ISSUE THREAD

**Issue by p-runge** [Marvin-Dem/Pokacid#42]
# ToDos

- [x] Remove light / dark toggle
- [x] Add vertical margin to logo
- [x] Add link to homepage to logo
