### ISSUE TITLE
Responsive List Page

### ISSUE THREAD

**Issue by p-runge** [Marvin-Dem/Pokacid#43]
# ToDos

- [x] Make the list page work with a major grid just like the details page
- [x] Place all items on the grid for desktop
- [x] Place all items on the grid for mobile

**Comment by Marvin-Dem** [comment]
Mobile first!

**Comment by Marvin-Dem** [comment]
Fix Play Button

**Comment by Marvin-Dem** [comment]
Tasks for Tuesday:
-fix sprite size. 
-Grid List concept + build
-PlayButton size
