### ISSUE TITLE
Evolution Details

### ISSUE THREAD

**Issue by p-runge** [Marvin-Dem/Pokacid#48]
Jedes Pokémon ist Teil einer Evolutionsreihe. Viele dieser Reihen verlaufen gradlinig, einige bestehen nur aus dem Pokémon selbst, andere wiederum folgen einer Baumstruktur.

# ToDos

## Design

Das bisherige Design braucht ein Update um auch verzweigte Evolutionen darstellen zu können – entweder auf einen Blick oder via Interaktion des Users.

Beachte dabei, dass es schwierig sein könnte eine "Default Evolutionsreihe" darzustellen. Wenn man also Evoli anzeigt, welche Entwicklung soll dann standardmäßig dargestellt werden? Aquana? Was ist, wenn man dann aber Blitza aufruft? Zeigt das auch "Evoli -> Aquana" an? Hier wäre auf Edge-Cases zu achten.

### Gradlinig verlaufende, reine "Level-Up" Evolutionen

Beispiel: Bisasam

- [x] Sprites der einzelnen Pokémon werden gerendert
- [x] Die Sprites der Evolutionsreihe werden untereinander dargestellt
- [x] Die Sprites werden mit Pfeilen verbunden
- [x] An jedem Pfeil hängt das Level, bei dem die Entwicklung stattfindet

### Gradlinig verlaufende Evolutionen mit anderen Entwicklungsarten

Beispiel: Sterndu

- [x] Entwicklungssteine
- [x] Freundschaft
- [x] Andere?

### Verzweigte Evolutionen

Beispiele: Evoli, Myrapla, Seeper

- [x] Alle möglichen Evolutionen werden dargestellt (direkt oder indirekt)

# Update

Das Design wurde zu einer 2-dimensionalen Ansicht angepasst. Dieses ist vom Layout her auf größtenteils fertg. Es fehlen allerdings noch genauere Details aus den referenzierten Entitäten (Sprite, Name im Title Case, etc.).

**Comment by p-runge** [comment]
Grobe Vorlage: https://www.pokewiki.de/Bisasam#Zucht_und_Entwicklung

Als nächster Step sollen die Details der entwickelten Pokémon mit gefetcht werden, damit sie in der Komponente angezeigt werden können (z.B. Sprite).
